<?php

/**
 * @file
 * Contains migrate_standrews.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_standrews_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_standrews module.
    case 'help.page.migrate_standrews':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('St.Andrews Archive Migration') . '</p>';
      return $output;

    default:
  }
}
